/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem;

/**
 *
 * @author nico
 */
public class AttendanceForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AttendanceForm.class.getName());

    /**
     * Creates new form AttendanceForm
     */
    public AttendanceForm() {
 initComponents();
    setSize(800, 600);
    setLocationRelativeTo(null);
    setTitle("Attendance Record");
    txtDate.setText(new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
    loadSubjects();
    loadStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelFilter = new javax.swing.JPanel();
        lblSubject = new javax.swing.JLabel();
        cmbSubject = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lblTitle.setText("Attendance Record");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblSubject.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubject.setText("Subject:");

        cmbSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDate.setText("Date:");

        txtDate.addActionListener(this::txtDateActionPerformed);

        javax.swing.GroupLayout panelFilterLayout = new javax.swing.GroupLayout(panelFilter);
        panelFilter.setLayout(panelFilterLayout);
        panelFilterLayout.setHorizontalGroup(
            panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilterLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelFilterLayout.setVerticalGroup(
            panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilterLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject)
                    .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Full Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAttendance);

        btnSave.setText("Save Attendance");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
        // This automatically puts today's date in the field
txtDate.setText(new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
    java.sql.Connection conn = getConnection();
    String date = txtDate.getText();
    String subjectName = cmbSubject.getSelectedItem().toString();
    
    // Get subject ID
    String sqlSubject = "SELECT subject_id FROM subjects WHERE subject_name=?";
    java.sql.PreparedStatement pstSubject = conn.prepareStatement(sqlSubject);
    pstSubject.setString(1, subjectName);
    java.sql.ResultSet rsSubject = pstSubject.executeQuery();
    
    if(!rsSubject.next()){
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Subject not found!");
        return;
    }
    int subjectId = rsSubject.getInt("subject_id");
    
    // Save attendance for each student
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) tblAttendance.getModel();
    
    for(int i = 0; i < model.getRowCount(); i++){
        String studentId = model.getValueAt(i, 0).toString();
        String status = model.getValueAt(i, 2).toString();
        
        // Check if attendance already exists
        String sqlCheck = "SELECT * FROM attendance WHERE student_id=? AND subject_id=? AND date=?";
        java.sql.PreparedStatement pstCheck = conn.prepareStatement(sqlCheck);
        pstCheck.setString(1, studentId);
        pstCheck.setInt(2, subjectId);
        pstCheck.setString(3, date);
        java.sql.ResultSet rsCheck = pstCheck.executeQuery();
        
        if(rsCheck.next()){
            // Update existing attendance
            String sqlUpdate = "UPDATE attendance SET status=? WHERE student_id=? AND subject_id=? AND date=?";
            java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
            pstUpdate.setString(1, status);
            pstUpdate.setString(2, studentId);
            pstUpdate.setInt(3, subjectId);
            pstUpdate.setString(4, date);
            pstUpdate.executeUpdate();
        } else {
            // Insert new attendance
            String sqlInsert = "INSERT INTO attendance (student_id, subject_id, date, status) VALUES (?,?,?,?)";
            java.sql.PreparedStatement pstInsert = conn.prepareStatement(sqlInsert);
            pstInsert.setString(1, studentId);
            pstInsert.setInt(2, subjectId);
            pstInsert.setString(3, date);
            pstInsert.setString(4, status);
            pstInsert.executeUpdate();
        }
    }
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Attendance saved successfully!");
    conn.close();
} catch(Exception e){
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new ProfessorDashboard().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private java.sql.Connection getConnection() throws Exception {
    Class.forName("com.mysql.cj.jdbc.Driver");
    return java.sql.DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/student_management_system",
        "root", ""
    );
}
    
    private void loadSubjects() {
    try {
        java.sql.Connection conn = getConnection();
        String sql = "SELECT * FROM subjects";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        cmbSubject.removeAllItems();
        while(rs.next()){
            cmbSubject.addItem(rs.getString("subject_name"));
        }
        conn.close();
    } catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error loading subjects: " + e.getMessage());
    }
}
    
    private void loadStudents() {
try {
        java.sql.Connection conn = getConnection();
        String sql = "SELECT * FROM students";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        javax.swing.table.DefaultTableModel model = 
            new javax.swing.table.DefaultTableModel(
                new String[]{"Student ID", "Full Name", "Status"}, 0
            ){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 2;
                }
            };
        
        while(rs.next()){
            String studentId = rs.getString("student_id");
            String fullName = rs.getString("full_name");
            
            // Check if attendance already saved for today
            String today = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
            String sqlCheck = "SELECT status FROM attendance WHERE student_id=? AND date=?";
            java.sql.PreparedStatement pstCheck = conn.prepareStatement(sqlCheck);
            pstCheck.setString(1, studentId);
            pstCheck.setString(2, today);
            java.sql.ResultSet rsCheck = pstCheck.executeQuery();
            
            String status = "present"; // default
            if(rsCheck.next()){
                status = rsCheck.getString("status"); // load saved status
            }
            
            model.addRow(new Object[]{studentId, fullName, status});
        }
        tblAttendance.setModel(model);
        
        // Add dropdown for Status column
        javax.swing.JComboBox<String> statusCombo = new javax.swing.JComboBox<>();
        statusCombo.addItem("present");
        statusCombo.addItem("absent");
        statusCombo.addItem("tardy");
        tblAttendance.getColumnModel().getColumn(2).setCellEditor(
            new javax.swing.DefaultCellEditor(statusCombo));
        
        conn.close();
    } catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error loading students: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AttendanceForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbSubject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelFilter;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
