/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem;

/**
 *
 * @author nico
 */
public class StudentRecords extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentRecords.class.getName());

    /**
     * Creates new form StudentRecords
     */
    public StudentRecords() {
        initComponents();
            setSize(900, 500);
    setLocationRelativeTo(null);
    setTitle("Student Records");
        tblStudents.setDefaultEditor(Object.class, null);
    loadStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelInput = new javax.swing.JPanel();
        lblStudentID = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblSection = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtSection = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lblTitle.setText("Student Records");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(334, 334, 334))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblStudentID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStudentID.setText("Student ID:");

        lblFullName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFullName.setText("Full Name:");

        lblCourse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCourse.setText("Course:");

        lblSection.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSection.setText("Section:");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lblFullName)
                        .addGap(18, 18, 18)
                        .addComponent(txtFullName))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblEmail))
                        .addGap(35, 35, 35)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSection, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCourse)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lblStudentID)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelInputLayout.createSequentialGroup()
                                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblStudentID)
                                            .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFullName))
                                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblCourse))
                            .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSection))
                    .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(14, 14, 14))
        );

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Full Name", "Course", "Section", "Email"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(txtStudentID.getText().isEmpty() || txtFullName.getText().isEmpty()){
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Student ID and Full Name are required!");
    return;
}
try {
    java.sql.Connection conn = getConnection();
    String sql = "INSERT INTO students (student_id, full_name, course, section, email) VALUES (?,?,?,?,?)";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, txtStudentID.getText());
    pst.setString(2, txtFullName.getText());
    pst.setString(3, txtCourse.getText());
    pst.setString(4, txtSection.getText());
    pst.setString(5, txtEmail.getText());
    pst.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Student added successfully!");
    loadStudents();
    clearFields();
    conn.close();
} catch(Exception e){
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
clearFields();   
// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(txtStudentID.getText().isEmpty()){
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Please select a student to delete!");
    return;
}
int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
    "Are you sure you want to delete this student?",
    "Delete", javax.swing.JOptionPane.YES_NO_OPTION);
if(confirm == javax.swing.JOptionPane.YES_OPTION){
    try {
        java.sql.Connection conn = getConnection();
        String sql = "DELETE FROM students WHERE student_id=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtStudentID.getText());
        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Student deleted successfully!");
        loadStudents();
        clearFields();
        conn.close();
    } catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error: " + e.getMessage());
    }
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
if(txtStudentID.getText().isEmpty()){
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Please select a student to update!");
    return;
}
try {
    java.sql.Connection conn = getConnection();
    
    // Get the original student ID from the table
    int row = tblStudents.getSelectedRow();
    String originalID = tblStudents.getValueAt(row, 0).toString();
    
    // Delete old record
    String deleteSql = "DELETE FROM students WHERE student_id=?";
    java.sql.PreparedStatement deletePst = conn.prepareStatement(deleteSql);
    deletePst.setString(1, originalID);
    deletePst.executeUpdate();
    
    // Insert new record with updated info
    String insertSql = "INSERT INTO students (student_id, full_name, course, section, email) VALUES (?,?,?,?,?)";
    java.sql.PreparedStatement insertPst = conn.prepareStatement(insertSql);
    insertPst.setString(1, txtStudentID.getText());
    insertPst.setString(2, txtFullName.getText());
    insertPst.setString(3, txtCourse.getText());
    insertPst.setString(4, txtSection.getText());
    insertPst.setString(5, txtEmail.getText());
    insertPst.executeUpdate();
    
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Student updated successfully!");
    loadStudents();
    clearFields();
    conn.close();
} catch(Exception e){
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        int row = tblStudents.getSelectedRow();
if(row >= 0){
    txtStudentID.setText(tblStudents.getValueAt(row, 0).toString());
    txtFullName.setText(tblStudents.getValueAt(row, 1).toString());
    txtCourse.setText(tblStudents.getValueAt(row, 2).toString());
    txtSection.setText(tblStudents.getValueAt(row, 3).toString());
    txtEmail.setText(tblStudents.getValueAt(row, 4).toString());
}
    }//GEN-LAST:event_tblStudentsMouseClicked

    private java.sql.Connection getConnection() throws Exception {
    Class.forName("com.mysql.cj.jdbc.Driver");
    return java.sql.DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/student_management_system",
        "root", ""
    );
}
    
    private void loadStudents() {
try {
        java.sql.Connection conn = getConnection();
        String sql = "SELECT * FROM students";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        // SET UP TABLE MODEL WITH CORRECT COLUMNS
        javax.swing.table.DefaultTableModel model = 
            new javax.swing.table.DefaultTableModel(
                new String[]{"Student ID", "Full Name", "Course", "Section", "Email"}, 0
            );
        
        while(rs.next()){
            model.addRow(new Object[]{
                rs.getString("student_id"),
                rs.getString("full_name"),
                rs.getString("course"),
                rs.getString("section"),
                rs.getString("email")
            });
        }
        tblStudents.setModel(model);
        // PREVENT EDITING AFTER MODEL IS SET
        tblStudents.setDefaultEditor(Object.class, null);
        conn.close();
    } catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error loading students: " + e.getMessage());
    }
}
    
    private void clearFields() {
    txtStudentID.setText("");
    txtFullName.setText("");
    txtCourse.setText("");
    txtSection.setText("");
    txtEmail.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentRecords().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
